### ISSUE TITLE
Help for Mac users.

### ISSUE THREAD

**Issue by ShauryaKS** [IITGuwahati-AI/Learning-Content#238]
You had not mentioned anything for Mac users. Is it not possible for Mac users to pursue this course?  If yes, please give some information on how to proceed.

**Comment by abhilashreddys** [comment]
It's possible in MAC OS also we just updated the repo please go check or open terminal and execute these commands.
> Open Terminal
```shell
$ xcode-select --install
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ curl -O https://bootstrap.pypa.io/ez_setup.py
$ python3 ez_setup.py
$ curl -O https://bootstrap.pypa.io/get-pip.py
$ python3 get-pip.py
```

**Comment by cbikramjit** [comment]
Command python3 is not recognised. Do I have to edit path variable?
